---
apiVersion: v1
kind: Service
metadata:
  name: dice
spec:
  selector:
    app: dice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice
  template:
    metadata:
      labels:
        app: dice
        foo: bar
    spec:
      containers:
        - name: dice
          image: dice:1.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
